// <auto-generated />
using System;
using LemonLabs.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LemonLabs.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260712210406_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("LemonLabs.Web.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChefId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChefId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("LemonLabs.Web.Models.Chef", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Specialty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearsExperience")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Chefs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Plant-forward seasonal cooking.",
                            HourlyRate = 65m,
                            Name = "Chef Maria Alvarez",
                            Specialty = 2,
                            YearsExperience = 8
                        },
                        new
                        {
                            Id = 2,
                            Bio = "High-protein performance meals.",
                            HourlyRate = 85m,
                            Name = "Chef Daniel Osei",
                            Specialty = 5,
                            YearsExperience = 12
                        });
                });

            modelBuilder.Entity("LemonLabs.Web.Models.Farm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Farms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Family-owned organic vegetable farm.",
                            Location = "Boulder, CO",
                            Name = "Green Valley Farm"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Pasture-raised poultry and eggs.",
                            Location = "Fort Collins, CO",
                            Name = "Sunrise Pastures"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Seasonal fruit orchard.",
                            Location = "Longmont, CO",
                            Name = "Rocky Creek Orchards"
                        });
                });

            modelBuilder.Entity("LemonLabs.Web.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FarmId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOrganic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeasonalAvailability")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FarmId = 1,
                            IsOrganic = true,
                            Name = "Kale",
                            SeasonalAvailability = "Fall-Winter"
                        },
                        new
                        {
                            Id = 2,
                            FarmId = 1,
                            IsOrganic = true,
                            Name = "Sweet Potato",
                            SeasonalAvailability = "Fall"
                        },
                        new
                        {
                            Id = 3,
                            FarmId = 2,
                            IsOrganic = true,
                            Name = "Free-Range Eggs",
                            SeasonalAvailability = "Year-round"
                        },
                        new
                        {
                            Id = 4,
                            FarmId = 2,
                            IsOrganic = false,
                            Name = "Chicken Breast",
                            SeasonalAvailability = "Year-round"
                        },
                        new
                        {
                            Id = 5,
                            FarmId = 3,
                            IsOrganic = true,
                            Name = "Blueberries",
                            SeasonalAvailability = "Summer"
                        });
                });

            modelBuilder.Entity("LemonLabs.Web.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Allergens")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("Calories")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DietType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerServing")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Allergens = "None",
                            Calories = 480,
                            Category = 1,
                            Description = "Roasted sweet potato over sauteed kale.",
                            DietType = 2,
                            Name = "Kale & Sweet Potato Bowl",
                            PricePerServing = 8.50m
                        },
                        new
                        {
                            Id = 2,
                            Allergens = "Eggs",
                            Calories = 520,
                            Category = 0,
                            Description = "High-protein breakfast plate.",
                            DietType = 5,
                            Name = "Grilled Chicken & Eggs Breakfast",
                            PricePerServing = 7.00m
                        },
                        new
                        {
                            Id = 3,
                            Allergens = "Gluten",
                            Calories = 350,
                            Category = 0,
                            Description = "Vegetarian oats with fresh blueberries.",
                            DietType = 1,
                            Name = "Blueberry Overnight Oats",
                            PricePerServing = 5.25m
                        });
                });

            modelBuilder.Entity("LemonLabs.Web.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Quantity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IngredientId = 1,
                            Quantity = "2 cups",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 2,
                            IngredientId = 2,
                            Quantity = "1 medium",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 3,
                            IngredientId = 3,
                            Quantity = "2 eggs",
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 4,
                            IngredientId = 4,
                            Quantity = "4 oz",
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 5,
                            IngredientId = 5,
                            Quantity = "1/2 cup",
                            RecipeId = 3
                        });
                });

            modelBuilder.Entity("LemonLabs.Web.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Allergies")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("DailyCalorieGoal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DietType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WeeklyBudget")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("LemonLabs.Web.Models.Booking", b =>
                {
                    b.HasOne("LemonLabs.Web.Models.Chef", "Chef")
                        .WithMany("Bookings")
                        .HasForeignKey("ChefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LemonLabs.Web.Models.UserProfile", "UserProfile")
                        .WithMany("Bookings")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chef");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("LemonLabs.Web.Models.Ingredient", b =>
                {
                    b.HasOne("LemonLabs.Web.Models.Farm", "Farm")
                        .WithMany("Ingredients")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("LemonLabs.Web.Models.RecipeIngredient", b =>
                {
                    b.HasOne("LemonLabs.Web.Models.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LemonLabs.Web.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("LemonLabs.Web.Models.Chef", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("LemonLabs.Web.Models.Farm", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("LemonLabs.Web.Models.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("LemonLabs.Web.Models.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("LemonLabs.Web.Models.UserProfile", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
